Updates to enableScripts docs
Add autolink support for keys such as `dependenciesMeta[].built`.

Improve error handling: Previously, a reference to an invalid key such as `dependenciesMeta.built` caused building the docs site to fail with the following error:

```
Cause: Cannot convert undefined or null to object
Details:
TypeError: Cannot convert undefined or null to object
    at Function.hasOwn (<anonymous>)
    at Array.find (<anonymous>)
```

Add cross-links between dependenciesMeta[].built docs and enableScripts docs.